[package]
name = "config"
version = "0.1.0"
edition.workspace = true
authors.workspace = true

[dependencies]
toml.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
